name: Atualizar JSON da ANP

on:
  schedule:
    - cron: '0 3 * * *'  # Executa todos os dias às 03:00 UTC
  workflow_dispatch:     # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install pandas openpyxl

      - name: Executar script de conversão
        run: python converter_excel_para_json.py

      - name: Commit e push do JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add cnpjs_validos.json
          if git diff --cached --quiet; then
            echo "Nenhuma alteração detectada no JSON. Nada para commitar."
          else
            git commit -m "Atualização automática do JSON"
            git push
          fi
